language: go
sudo: false

go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "master"

matrix:
  allow_failures:
    - go: master

install:
  - go install

script:
  - go test -v ./...
  - diff <(goimports -d *.go) <(printf "")
  - diff <(golint *.go) <(printf "")
